@hostname=localhost
@port=3333
@host={{hostname}}:{{port}}

# Create a new user
# @name register
POST http://{{host}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "name": "John Doe",
  "password": "12345678"
}

###

# Try to create a user with invalid data (400)
POST http://{{host}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "not-an-email",
  "name": "Jo",
  "password": "123"
}

###

# Login user by email and password
# @name login
POST http://{{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "12345678"
}

###

# Try to login user by email and wrong password (401)
POST http://{{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "wrong-password"
}

###

# Try to login user by fake email (404)
POST http://{{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "fake-email@example.com",
  "password": "12345678"
}

###

# Get user by ID
GET http://{{host}}/api/auth/{{login.response.body.id}} HTTP/1.1
Authorization: Bearer {{login.response.body.accessToken}}

###

# Try to get user without a token (401)
GET http://{{host}}/api/auth/{{login.response.body.id}} HTTP/1.1

###

# Try to get user by invalid ID (400)
GET http://{{host}}/api/auth/123 HTTP/1.1
Authorization: Bearer {{login.response.body.accessToken}}

###

# Get a new pair of tokens (a refresh token can be used only once)
# @name refresh
POST http://{{host}}/api/auth/refresh HTTP/1.1
Authorization: Bearer {{login.response.body.refreshToken}}
